config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum:5, maximum: 50 }
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only allows valid emails" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  def index
    @courses = Course.all
  end

  def new

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end
  
  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash[:success] = "You have successfully updated your profile"
      redirect_to student_path(@student)
    else
      render 'edit'
    end
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "You have successfully signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  private 

  def student_params
    params.require(:student).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Courses Listing</h3>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
  <div class="col s12 m6 l6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
        <p><%= course.description %></p>
      </div>
      <div class="card-action">
        <a href="#">Enroll</a>
        <a href="#">Info</a>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h1>New Pages</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future on your hand.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2019 Tech University
    <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header class="navbar-fixed">
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <a href="#" class="brand-logo right">Tech University</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to 'Courses', root_path %></li>
          <li><%= link_to 'Enrollments', about_path %></li>
          <li><%= link_to 'Students', students_path %></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>
    
<ul class="sidenav" id="mobile-demo">
  <li><a href="#">Courses</a></li>
  <li><a href="#">Enrollments</a></li>
  <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
</ul>

<% flash.each do |key, message| %>
  <div class="container">
    <div class="row" style="padding-top: 30px;">
      <div class="col s12 m12 l12">
        <div id="fade-out-target" class="card-panel red lighten-2">
          <span class="white-text">
            <%= message %>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render 'layouts/navigation' %>
    <main class="container">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/students/edit.html.erb
<% if @student.errors.any? %>
  <div class="container">
    <div class="row" style="padding-top: 30px;">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(@student.errors.count, "error") %></strong>
            prohibited your profile from being created
            <ul>
              <% @student.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>    
  </div>
<% end %>

<div class="container" style="padding-top: 30px;">
  <div class="row center">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Edit your profile</h3>
        <div class="row">
          <%= form_for(@student, :html => {:class => "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name%>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.submit "Submit changes", :class => "btn orange waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Students Directory</h3>
  </div>
</div>

<div class="row">
  <% @students.each do |student| %>
  <div class="col s12 m6 l6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= student.name %></span>
        <p>Email: <%= student.email %></p>
        <p>Course Enrollments: None</p>
      </div>
      <div class="card-action">
        <%= link_to '<i class="material-icons left">account_box</i>View Profile'.html_safe, student_path(student.id), class: "waves-effect waves-light btn" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/students/new.html.erb
<% if @student.errors.any? %>
  <div class="container">
    <div class="row" style="padding-top: 30px;">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(@student.errors.count, "error") %></strong>
            prohibited your profile from being created
            <ul>
              <% @student.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>    
  </div>
<% end %>

<div class="container" style="padding-top: 30px;">
  <div class="row center">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header">Sign up!</h3>
        <div class="row">
          <%= form_for(@student, :html => {:class => "col s12"}) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocus: true %>
                <%= f.label :name%>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.submit "Sign up", :class => "btn orange waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/show.html.erb
<div class="row">
  <div class="col s12 m6 l6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= @student.name %></span>
        <p>Email: <%= @student.email %></p>
        <p>Course Enrollments: None</p>
      </div>
    </div>
    <%= link_to '<i class="material-icons left">create</i>Edit your profile'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn" %>
  </div>
</div>